# -*- coding: utf-8 -*-
"""26_05_2023.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1PCf2l13xJwXF2uYz8FySWM5MgKZoDIlW
"""

print ("Привет мир")